name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install Rust cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: cargo
      - name: Install Scryer Prolog
        uses: logtalk-actions/setup-scryer-prolog@master
        with:
          scryer-prolog-version: latest
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        run: logtalk_tester -p scryer